name: Test

on:
  push:
  pull_request:

env:
  JULIA_GITHUB_ACTIONS_CI: ON

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        name: "Test"
